### ISSUE TITLE
Global variables

### ISSUE THREAD

**Issue by tbtommyb** [GlobeTownDevs/stopwatch#2]
Your .js file adds lots of global variables (lines 1 -7). Maybe you could move everything to be inside the `stopwatch` object you make on line 7, or use a [module pattern](http://www.adequatelygood.com/JavaScript-Module-Pattern-In-Depth.html)?

**Comment by marisid** [comment]
Good point for big chunks of code and future instances. Refactoring our code to follow your suggestion would take us rather long now without affecting our functionality. But very good point :smile:
