### ISSUE TITLE
Clarity on asynchronous test

### ISSUE THREAD

**Issue by njsfield** [GlobeTownDevs/stopwatch#3]
``` javascript
 it('should start displaying seconds when milliseconds count is greater than 999', function(done) {
    expect(Math.abs(s.innerHTML)).toBe(2);
    done();
  });
```

The expect function should just check if ms is greater than 999, 
Currently the test is being too specific and checking that ~2 seconds is displayed

**Comment by marisid** [comment]
The point of this test was to prompt the next step in the development of the app, which was to have it start displaying seconds (previously it was just showing milliseconds). We chose a specific (small) amount of time to run the test to ensure that seconds would start appearing.
