### ISSUE TITLE
Unnecessary preventDefault

### ISSUE THREAD

**Issue by tbtommyb** [GlobeTownDevs/stopwatch#7]
You don't need to call `preventDefault` in the handlers because clicking on a button doesn't have any default behaviour. I think you only need to use that for `<a>` tags that would otherwise take you to a new page.

**Comment by marisid** [comment]
Oh, right, I didn't know that - thanks. So, it's redundant in our case but it doesn't harm to have it there in case the browser support changes in the future. So, it acts as a 'normalising' rule I guess.
